// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Location struct {
	State   string `json:"state"`
	City    string `json:"city"`
	ZipCode int    `json:"zip_code"`
}

type Name struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

type NewProfile struct {
	FirstName   *string `json:"first_name"`
	LastName    *string `json:"last_name"`
	State       *string `json:"state"`
	City        *string `json:"city"`
	ZipCode     *int    `json:"zip_code"`
	Email       *string `json:"email"`
	Description *string `json:"description"`
}

type ProfileQl struct {
	ID          string    `json:"id"`
	Name        *Name     `json:"name"`
	Location    *Location `json:"location"`
	Email       string    `json:"email"`
	Skills      []*Skill  `json:"skills"`
	Description string    `json:"description"`
}

type Skill struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"Description"`
}
